// const promise = new Promise((resolve, reject) => {
//     setTimeout(()=>{
//         reject('this is my resolved data');
//        }, 1500);
// });


// promise.then((data) => {
//     console.log(data);
// }).catch((e) => {
//     console.log('error occured',e);
// });